### ISSUE TITLE
Bad Gateway

### ISSUE THREAD

**Issue by masihxperes** [yonggekkk/doprax-xray#1]
i do like your YouTube but when i click my https link i have Bad Gateway

**Comment by paradoxlaby** [comment]
Hi dear and thanks. 
me too, I have Bad Gateway

**Comment by masihxperes** [comment]
hi 
i use cdn link goes correct but in v2rayn i cant connect i have ping of both link

**Comment by yonggekkk** [comment]
There are too many people currently using it, it is estimated that it will be blocked
