### ISSUE TITLE
构建docker镜像时报错

### ISSUE THREAD

**Issue by yx10010** [yonggekkk/Doprax-Xray#10]
点赞fork后构建docker镜像出现下面错误，~大佬能不能提示一下  百度谷歌都没找到答案

ERROR: invalid tag "***/:latest": invalid reference format
Error: buildx failed with: ERROR: invalid tag "***/:latest": invalid reference format

**Comment by yonggekkk** [comment]
使用的人太多，dop容易崩。。等下再试试吧
