### ISSUE TITLE
vmess同样的配置pc端不能访问，手机可以访问。

### ISSUE THREAD

**Issue by MaybeQHL** [yonggekkk/Doprax-Xray#23]
v2rayNv5.39

**Comment by yonggekkk** [comment]
设置问题吧，发配置图

**Comment by MaybeQHL** [comment]
可以了。DNS刷新一下就好了。大佬我还想问下 这个免费容器可以用多久啊，一个月多少 自己一个人用会不会被封

**Comment by yonggekkk** [comment]
> 可以了。DNS刷新一下就好了。大佬我还想问下 这个免费容器可以用多久啊，一个月多少流量， 自己一个人用会不会被封

目前无限制！容易崩！以后还会变！所以我停更了！等官方稳定再说

**Comment by MaybeQHL** [comment]
好的
