### ISSUE TITLE
可以增加一个服务器端口配置的环境变量吗？

### ISSUE THREAD

**Issue by yorsun** [yonggekkk/doprax-xray#3]
443，已经被墙了。

**Comment by yonggekkk** [comment]
> 443，已经被墙了。

80，8880，8080这类的http端口怎么样？

**Comment by yorsun** [comment]
80是可以的，8880，8080不行。网站是可以正常打开的。

**Comment by yonggekkk** [comment]
> 80是可以的，8880，8080不行。网站是可以正常打开的。

好的，收到

**Comment by yorsun** [comment]
大约什么时候有更新？

**Comment by yonggekkk** [comment]
> 大约什么时候有更新？

要月底了吧，其实在Herku的视频教程中就操作过了。

**Comment by yorsun** [comment]
哪个视频？我研究研究，方便贴个链接

**Comment by yonggekkk** [comment]
> 哪个视频？我研究研究，方便贴个链接

[workers被墙第二期吧。](https://youtu.be/yqyaZzL_BJc)
