### ISSUE TITLE
大佬，是否能增加一个某些网站单独走warp的分流功能？比如netflix之类的？

### ISSUE THREAD

**Issue by lovelygfj** [yonggekkk/doprax-xray#8]

**Comment by lovelygfj** [comment]
我看fscarmen的脚本里写了有这个功能。
但他这个脚本，在Doprax部署后，运行有问题，获取不到argo地址，应该是argo没连接上
https://github.com/fscarmen2/Argo-X-Container-PaaS

**Comment by yonggekkk** [comment]
会加的！！
